# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Paginate Example - 03 Tags
email: jekyll@sverrirs.com
description: > # this means to ignore newlines until "baseurl:"
  Shows how the jekyll-paginate-v2 gem can be used to paginate on tags and categories together.
baseurl: "/v2_myblog" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  sverrirs

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-paginate-v2
  - jekyll-assets
  - jekyll-paginate-content
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
  
# Collection configurations
collections:
  biography:
    output: true
    permalink: /biography/:path/
  fantasy:
    output: true
    permalink: /fantasy/:path/
  romance: 
    output: true
    permalink: /romance/:path/

############################################################
# Site configuration for the Auto-Pages feature
# The values here represent the defaults if nothing is set
autopages:

  # Site-wide kill switch, disable here and it doesn't run at all 
  enabled: true

  # Category pages, omit entire config element to disable
  categories: 
    # Optional, the list of layouts that should be processed for every category found in the site
    layouts: 
      - 'autopage_category.html'
    # Optional, the title that each category paginate page should get (:cat is replaced by the Category name)
    title: 'Posts in category :cat'
    # Optional, the permalink for the  pagination page (:cat is replaced), 
    # the pagination permalink path is then appended to this permalink structure
    permalink: '/category/:cat'

  # Collection pages, omit to disable
  collections:
    layouts: 
      - 'autopage_collection.html'
    title: 'Posts in My collection :coll' # :coll is replaced by the collection name
    permalink: '/collection/:coll'
  
  # Tag pages, omit to disable
  tags:
    layouts: 
      - 'autopage_tags.html'
    title: 'Posts tagged with :tag' # :tag is replaced by the tag name
    permalink: '/tag/:tag'
    
  
# This site uses the pretty permalink structure, this renders all urls with a slash / at the end and 
# no file endings, I guess that is considered pretty :)
permalink: pretty

# Pagination Settings
pagination:
  enabled: true
  per_page: 3
  permalink: '/:num/'
  title: ':title | :num of :max'
  limit: 0
  sort_field: 'date'
  sort_reverse: true
 # extension: htm
 # indexpage: 'default'
  trail: 
    before: 2
    after: 2

# https://github.com/jekyll/jekyll/issues/920#issuecomment-315503935
include: ['_pages']

header_pages:
  - "_pages/tmux.md"
  - "_pages/html_Lab.html"
  - "_pages/markdown_Lab.md"
  - "_pages/bs4_lab.html"
  - "_pages/about.md"
  - "asciinema/asciinema.html"

